from enum import Enum


class GatewayOpcode(Enum):
    DISPATCH_RECEIVE = 0
    HEARTBEAT_SEND_RECEIVE = 1
    IDENTIFY_SEND = 2
    PRESENCE_UPDATE_SEND = 3
    VOICE_STATE_UPDATE_SEND = 4
    RESUME_SEND = 6
    RECONNECT_RECEIVE = 7
    REQUEST_GUILD_MEMBERS_SEND = 8
    INVALID_SESSION_RECEIVE = 9
    HELLO_RECEIVE = 10
    HEARTBEAT_ACK_RECEIVE = 11
